import { NextResponse } from "next/server";
import { githubErrorPayload, githubFetch } from "@/lib/github/github-api";
import { getGitHubAccessToken } from "@/lib/github/github-session";

export const dynamic = "force-dynamic";

const repositoryPattern = /^[A-Za-z0-9_.-]+\/[A-Za-z0-9_.-]+$/;

export async function POST(request: Request) {
  const token = await getGitHubAccessToken();
  if (!token) return NextResponse.json({ error: "Connect GitHub before creating issues." }, { status: 401 });

  try {
    const body = (await request.json()) as {
      repository?: string;
      finding?: {
        title?: string;
        severity?: string;
        category?: string;
        evidence?: string;
        impact?: string;
        fix?: string;
        prompt?: string;
      };
    };
    if (!body.repository || !repositoryPattern.test(body.repository) || !body.finding?.title) {
      return NextResponse.json({ error: "Repository and finding are required." }, { status: 400 });
    }

    const finding = body.finding;
    const issueBody = `## Vibe readiness finding

**Severity:** ${finding.severity ?? "unknown"}
**Category:** ${finding.category ?? "General"}

### Evidence
${finding.evidence ?? "No evidence supplied."}

### Impact
${finding.impact ?? "No impact supplied."}

### Suggested fix
${finding.fix ?? "No fix supplied."}

### Implementation prompt
${finding.prompt ?? "No prompt supplied."}

---
Generated by Vibe launch-readiness auditor.`;
    const response = await githubFetch(`/repos/${body.repository}/issues`, {
      token,
      method: "POST",
      body: {
        title: `[Vibe] ${finding.title}`.slice(0, 256),
        body: issueBody.slice(0, 60_000),
      },
    });
    const issue = (await response.json()) as { number: number; html_url: string };
    return NextResponse.json({ number: issue.number, url: issue.html_url });
  } catch (error) {
    const payload = githubErrorPayload(error);
    return NextResponse.json(payload.body, { status: payload.status });
  }
}
